# Generated by Django 2.1.4 on 2018-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=256)),
                ('gprice', models.FloatField()),
                ('gmain_catalog', models.CharField(max_length=256, null=True)),
                ('gsales', models.CharField(max_length=256, null=True)),
                ('gvocation', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
