# Generated by Django 2.1.4 on 2018-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='gpub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
